In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a, a.shape

(array([1, 2, 3]), (3,))

In [3]:
print(np.argmax(a))
print(a.argmax())

2
2


In [10]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [21]:
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])
print(np.dot(c, d))

32


In [25]:
e = np.array([[2, 1], [1, 4]])
f = np.array([[1, 2, 0], [0, 1, 2]])
print(np.matmul(e, f))
print(np.dot(e, f))

[[2 5 2]
 [1 6 8]]
[[2 5 2]
 [1 6 8]]


In [27]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [28]:
A = np.arange(9).reshape(3, 3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
print(A.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
